import {
  blueBig1,
  blueBig2,
  blueBig3,
  blueDesk,
  blueMobile,
  bluePitch,
  blueSmall1,
  blueSmall2,
  blueSmall3,
  blueSmall4,
  energBig1,
  energBig2,
  energBig3,
  energDesk,
  energMobile,
  energPitch,
  energSmall1,
  energSmall2,
  energSmall3,
  energSmall4,
  Friendly,
  friendlyBig1,
  friendlyBig2,
  friendlyBig3,
  friendlyDesk,
  friendlyMobile,
  friendlyPitch,
  friendlySmall1,
  friendlySmall2,
  friendlySmall3,
  friendlySmall4,
  imgProject1,
  imgProject2,
  imgProject3,
  imgProject4,
  imgProject5,
  LeoMi,
  saborBig1,
  saborBig2,
  saborBig3,
  saborDesk,
  Sabordobem,
  saborMobile,
  saborPitch,
  saborSmall1,
  saborSmall2,
  saborSmall3,
  saborSmall4,
  vaptBig1,
  vaptBig2,
  vaptBig3,
  vaptDesk,
  vaptMobile,
  vaptPitch,
  vaptSmall1,
  vaptSmall2,
  vaptSmall3,
  vaptSmall4,
  vidProject1,
  vidProject2,
  vidProject3,
  vidProject4,
  vidProject5,
} from "../utils/utils";

export const projects = [
  {
    id: "Vapt-Vupt",
    title: "Vapt-Vupt",
    subtitle: "(Challenge - FIAP)",
    description:
      "Uma plataforma inovadora que utiliza inteligência artificial para te auxiliar na jornada de manutenção do seu carro.",
    image: imgProject1,
    video: vidProject1,
    link: "https://vapt-vupt.vercel.app/",
    year: "(2024) Fev - Set",
    youtube: "https://www.youtube.com/@Vapt-Vupt_Challenge",
    credits: [
      { name: "Leonardo Botelho", work: "Dev Back-End" },
      { name: "Mirian Bronzati", work: "Dev IA" },
    ],
    services: [
      "Web Development",
      "Web Design",
      "Branding",
      "Motion Design",
      "Video Editing",
    ],
    /* media */
    pitch: vaptPitch,
    desk: vaptDesk,
    mobile: vaptMobile,
    small1: vaptSmall1,
    small2: vaptSmall2,
    small3: vaptSmall3,
    small4: vaptSmall4,
    big1: vaptBig1,
    big2: vaptBig2,
    big3: vaptBig3,
    team: LeoMi,
  },
  {
    id: "Friendly",
    title: "Friendly",
    subtitle: "(Iniciação Científica - FIAP)",
    description:
      "Uma plataforma de Inteligência Artificial que te ajuda a construir uma vida mais leve e equilibrada cuidando da sua saúde mental e emocional.",
    image: imgProject2,
    video: vidProject2,
    link: "https://reco-facial-friendly.vercel.app/",
    year: "(2024) Fev - Set",
    youtube: "https://www.youtube.com/@friendly2024",
    credits: [
      { name: "Henrique Franco", work: "Auxiliar de projeto" },
      { name: "Humberto Vitalino", work: "Dev IA" },
      { name: "Kaian Gustavo", work: "Documentação" },
      { name: "Leonardo Botelho", work: "Dev Back-End" },
      { name: "Nicollas Guedes", work: "Líder do Projeto" },
    ],
    services: [
      "Web Development",
      "Web Design",
      "Branding",
      "Motion Design",
      "Video Editing",
    ],
    /* media */
    pitch: friendlyPitch,
    desk: friendlyDesk,
    mobile: friendlyMobile,
    small1: friendlySmall1,
    small2: friendlySmall2,
    small3: friendlySmall3,
    small4: friendlySmall4,
    big1: friendlyBig1,
    big2: friendlyBig2,
    big3: friendlyBig3,
    team: Friendly,
  },
  {
    id: "Energia",
    title: "Energia",
    subtitle: "(Global Solution 2 - FIAP)",
    description:
      "Uma plataforma que simplifica o acompanhamento do consumo de energia, com análises detalhadas e recomendações personalizadas para reduzir desperdícios.",
    image: imgProject3,
    video: vidProject3,
    link: "https://gs-sigma.vercel.app/",
    year: "(2024) Set",
    youtube: "https://www.youtube.com/@Energia-o7u",
    credits: [
      { name: "Leonardo Botelho", work: "Dev Back-End" },
      { name: "Mirian Bronzati", work: "Dev IA" },
    ],
    services: [
      "Web Development",
      "Web Design",
      "Branding",
      "Motion Design",
      "Video Editing",
    ],
    /* media */
    pitch: energPitch,
    desk: energDesk,
    mobile: energMobile,
    small1: energSmall1,
    small2: energSmall2,
    small3: energSmall3,
    small4: energSmall4,
    big1: energBig1,
    big2: energBig2,
    big3: energBig3,
    team: LeoMi,
  },
  {
    id: "BlueGuardians",
    title: "Blue Guardians",
    subtitle: "(Global Solution 1 - FIAP)",
    description:
      "Um quiz interativo sobre vida marinha e ecossistemas oceânicos, com o chatbot Professor Polvo para enriquecer sua experiência.",
    image: imgProject4,
    video: vidProject4,
    link: "https://global-solution-olive.vercel.app/",
    year: "(2024) Jun",
    youtube: "https://www.youtube.com/@BlueGuardiansGS",
    credits: [
      { name: "Leonardo Botelho", work: "Dev Back-End" },
      { name: "Mirian Bronzati", work: "Dev IA" },
    ],
    services: [
      "Web Development",
      "Web Design",
      "Branding",
      "Motion Design",
      "Video Editing",
    ],
    /* media */
    pitch: bluePitch,
    desk: blueDesk,
    mobile: blueMobile,
    small1: blueSmall1,
    small2: blueSmall2,
    small3: blueSmall3,
    small4: blueSmall4,
    big1: blueBig1,
    big2: blueBig2,
    big3: blueBig3,
    team: LeoMi,
  },
  {
    id: "Sabordobem",
    title: "Sabor do bem",
    subtitle: "(TCC - ETEC)",
    description:
      "Um App que conecta supermercados a ONGs e asilos para reduzir o desperdício de alimentos e distribuí-los a quem precisa.",
    image: imgProject5,
    video: vidProject5,
    link: "https://sabordobem.vercel.app/",
    year: "(2023) Fev - Set",
    youtube: "https://www.youtube.com/@SabordoBemTCC",
    credits: [
      { name: "Leonardo Andorni", work: "Dev Mobile" },
      { name: "Lorenzo Augusto", work: "Auxiliar de projeto" },
      { name: "Lucas Roque", work: "Dev Mobile" },
      { name: "Mariana Nikaido", work: "Documentação" },
    ],
    services: [
      "Web Development",
      "Web Design",
      "Branding",
      "Motion Design",
      "Video Editing",
    ],
    /* media */
    pitch: saborPitch,
    desk: saborDesk,
    mobile: saborMobile,
    small1: saborSmall1,
    small2: saborSmall2,
    small3: saborSmall3,
    small4: saborSmall4,
    big1: saborBig1,
    big2: saborBig2,
    big3: saborBig3,
    team: Sabordobem,
  },
];
